version: '3.8'
services:
  mlflow-server:
    image: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow

  jupyter-notebook:
    image: tvm-cuda-jupyter:latest
    ports:
      - "8888:8888"
    volumes:
      - /mlruns:/app/mlruns
      - /onnx_tvm.ipynb:/app/onnx_tvm.ipynb

volumes:
  mlflow-data:
  notebook-data:
